// Code generated by protoc-gen-go. DO NOT EDIT.
// source: ContractUpdate.proto

package proto

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

// Modify a smart contract instance to have the given parameter values. Any null field is ignored (left unchanged). If only the contractInstanceExpirationTime is being modified, then no signature is needed on this transaction other than for the account paying for the transaction itself. But if any of the other fields are being modified, then it must be signed by the adminKey. The use of adminKey is not currently supported in this API, but in the future will be implemented to allow these fields to be modified, and also to make modifications to the state of the instance. If the contract is created with no admin key, then none of the fields can be changed that need an admin signature, and therefore no admin key can ever be added. So if there is no admin key, then things like the bytecode are immutable. But if there is an admin key, then they can be changed. For example, the admin key might be a threshold key, which requires 3 of 5 binding arbitration judges to agree before the bytecode can be changed. This can be used to add flexibility to the mangement of smart contract behavior. But this is optional. If the smart contract is created without an admin key, then such a key can never be added, and its bytecode will be immutable.
type ContractUpdateTransactionBody struct {
	ContractID           *ContractID `protobuf:"bytes,1,opt,name=contractID,proto3" json:"contractID,omitempty"`
	ExpirationTime       *Timestamp  `protobuf:"bytes,2,opt,name=expirationTime,proto3" json:"expirationTime,omitempty"`
	AdminKey             *Key        `protobuf:"bytes,3,opt,name=adminKey,proto3" json:"adminKey,omitempty"`
	ProxyAccountID       *AccountID  `protobuf:"bytes,6,opt,name=proxyAccountID,proto3" json:"proxyAccountID,omitempty"`
	AutoRenewPeriod      *Duration   `protobuf:"bytes,7,opt,name=autoRenewPeriod,proto3" json:"autoRenewPeriod,omitempty"`
	FileID               *FileID     `protobuf:"bytes,8,opt,name=fileID,proto3" json:"fileID,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *ContractUpdateTransactionBody) Reset()         { *m = ContractUpdateTransactionBody{} }
func (m *ContractUpdateTransactionBody) String() string { return proto.CompactTextString(m) }
func (*ContractUpdateTransactionBody) ProtoMessage()    {}
func (*ContractUpdateTransactionBody) Descriptor() ([]byte, []int) {
	return fileDescriptor_97d278ba35610687, []int{0}
}

func (m *ContractUpdateTransactionBody) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ContractUpdateTransactionBody.Unmarshal(m, b)
}
func (m *ContractUpdateTransactionBody) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ContractUpdateTransactionBody.Marshal(b, m, deterministic)
}
func (m *ContractUpdateTransactionBody) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ContractUpdateTransactionBody.Merge(m, src)
}
func (m *ContractUpdateTransactionBody) XXX_Size() int {
	return xxx_messageInfo_ContractUpdateTransactionBody.Size(m)
}
func (m *ContractUpdateTransactionBody) XXX_DiscardUnknown() {
	xxx_messageInfo_ContractUpdateTransactionBody.DiscardUnknown(m)
}

var xxx_messageInfo_ContractUpdateTransactionBody proto.InternalMessageInfo

func (m *ContractUpdateTransactionBody) GetContractID() *ContractID {
	if m != nil {
		return m.ContractID
	}
	return nil
}

func (m *ContractUpdateTransactionBody) GetExpirationTime() *Timestamp {
	if m != nil {
		return m.ExpirationTime
	}
	return nil
}

func (m *ContractUpdateTransactionBody) GetAdminKey() *Key {
	if m != nil {
		return m.AdminKey
	}
	return nil
}

func (m *ContractUpdateTransactionBody) GetProxyAccountID() *AccountID {
	if m != nil {
		return m.ProxyAccountID
	}
	return nil
}

func (m *ContractUpdateTransactionBody) GetAutoRenewPeriod() *Duration {
	if m != nil {
		return m.AutoRenewPeriod
	}
	return nil
}

func (m *ContractUpdateTransactionBody) GetFileID() *FileID {
	if m != nil {
		return m.FileID
	}
	return nil
}

func init() {
	proto.RegisterType((*ContractUpdateTransactionBody)(nil), "proto.ContractUpdateTransactionBody")
}

func init() { proto.RegisterFile("ContractUpdate.proto", fileDescriptor_97d278ba35610687) }

var fileDescriptor_97d278ba35610687 = []byte{
	// 284 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x5c, 0x90, 0xd1, 0x4a, 0xc3, 0x30,
	0x14, 0x86, 0xe9, 0xc4, 0x3a, 0x22, 0xae, 0x33, 0x78, 0x51, 0x06, 0x82, 0x0c, 0x1c, 0x5e, 0x15,
	0xd4, 0x1b, 0xbd, 0xb4, 0x2b, 0xc2, 0xd8, 0xcd, 0x08, 0xf5, 0x01, 0x8e, 0xe9, 0xd1, 0x46, 0x6c,
	0x12, 0xd2, 0x54, 0xd7, 0xb7, 0xf4, 0x91, 0xa4, 0x69, 0x2c, 0xae, 0x57, 0xe5, 0x9c, 0xff, 0xfb,
	0xfa, 0x1f, 0x42, 0x2e, 0xd6, 0x4a, 0x5a, 0x03, 0xdc, 0xbe, 0xe8, 0x02, 0x2c, 0x26, 0xda, 0x28,
	0xab, 0xe8, 0xb1, 0xfb, 0x2c, 0xe6, 0x29, 0xd4, 0x82, 0xe7, 0xad, 0xc6, 0xba, 0x0f, 0x16, 0xb3,
	0xac, 0x31, 0x60, 0x85, 0x92, 0x7e, 0x8e, 0x72, 0x51, 0x61, 0x6d, 0xa1, 0xd2, 0xfd, 0x62, 0xf9,
	0x33, 0x21, 0x97, 0x87, 0xbf, 0xcc, 0x0d, 0xc8, 0x1a, 0x78, 0x27, 0xa5, 0xaa, 0x68, 0xe9, 0x2d,
	0x21, 0xdc, 0x03, 0x9b, 0x2c, 0x0e, 0xae, 0x82, 0x9b, 0xd3, 0xbb, 0xf3, 0xde, 0x4e, 0xd6, 0x43,
	0xc0, 0xfe, 0x41, 0xf4, 0x81, 0xcc, 0x70, 0xaf, 0x45, 0xdf, 0xdc, 0x35, 0xc6, 0x13, 0xa7, 0xcd,
	0xbd, 0x36, 0x1c, 0xc1, 0x46, 0x1c, 0x5d, 0x91, 0x29, 0x14, 0x95, 0x90, 0x5b, 0x6c, 0xe3, 0x23,
	0xe7, 0x10, 0xef, 0x6c, 0xb1, 0x65, 0x43, 0xd6, 0x35, 0x68, 0xa3, 0xf6, 0xed, 0x13, 0xe7, 0xaa,
	0x91, 0xdd, 0x61, 0xe1, 0x41, 0xc3, 0xb0, 0x67, 0x23, 0x8e, 0x3e, 0x92, 0x08, 0x1a, 0xab, 0x18,
	0x4a, 0xfc, 0xde, 0xa1, 0x11, 0xaa, 0x88, 0x4f, 0x9c, 0x1a, 0x79, 0xf5, 0xef, 0xc5, 0xd8, 0x98,
	0xa3, 0xd7, 0x24, 0x7c, 0x13, 0x9f, 0xb8, 0xc9, 0xe2, 0xa9, 0x33, 0xce, 0xbc, 0xf1, 0xec, 0x96,
	0xcc, 0x87, 0xe9, 0x8a, 0x2c, 0xb9, 0xaa, 0x92, 0x12, 0x0b, 0x34, 0x50, 0x42, 0x5d, 0xbe, 0x1b,
	0xd0, 0x65, 0x02, 0x5a, 0x78, 0xfe, 0x03, 0xbe, 0x60, 0x17, 0xbc, 0x86, 0x6e, 0xba, 0xff, 0x0d,
	0x00, 0x00, 0xff, 0xff, 0x4e, 0xb5, 0xb5, 0x10, 0xd3, 0x01, 0x00, 0x00,
}
