// Code generated by protoc-gen-go. DO NOT EDIT.
// source: TransactionReceipt.proto

package proto

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

// The consensus result for a transaction, which might not be currently known, or may  succeed or fail.
type TransactionStatus int32

const (
	TransactionStatus_UNKNOWN      TransactionStatus = 0
	TransactionStatus_SUCCESS      TransactionStatus = 1
	TransactionStatus_FAIL_INVALID TransactionStatus = 2
	TransactionStatus_FAIL_FEE     TransactionStatus = 3
	TransactionStatus_FAIL_BALANCE TransactionStatus = 4
)

var TransactionStatus_name = map[int32]string{
	0: "UNKNOWN",
	1: "SUCCESS",
	2: "FAIL_INVALID",
	3: "FAIL_FEE",
	4: "FAIL_BALANCE",
}

var TransactionStatus_value = map[string]int32{
	"UNKNOWN":      0,
	"SUCCESS":      1,
	"FAIL_INVALID": 2,
	"FAIL_FEE":     3,
	"FAIL_BALANCE": 4,
}

func (x TransactionStatus) String() string {
	return proto.EnumName(TransactionStatus_name, int32(x))
}

func (TransactionStatus) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_31337d5eb7330cd9, []int{0}
}

// The consensus result for a transaction, which might not be currently known, or may  succeed or fail.
type TransactionReceipt struct {
	Status               TransactionStatus `protobuf:"varint,1,opt,name=status,proto3,enum=proto.TransactionStatus" json:"status,omitempty"`
	AccountID            *AccountID        `protobuf:"bytes,2,opt,name=accountID,proto3" json:"accountID,omitempty"`
	FileID               *FileID           `protobuf:"bytes,3,opt,name=fileID,proto3" json:"fileID,omitempty"`
	ContractID           *ContractID       `protobuf:"bytes,4,opt,name=contractID,proto3" json:"contractID,omitempty"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *TransactionReceipt) Reset()         { *m = TransactionReceipt{} }
func (m *TransactionReceipt) String() string { return proto.CompactTextString(m) }
func (*TransactionReceipt) ProtoMessage()    {}
func (*TransactionReceipt) Descriptor() ([]byte, []int) {
	return fileDescriptor_31337d5eb7330cd9, []int{0}
}

func (m *TransactionReceipt) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TransactionReceipt.Unmarshal(m, b)
}
func (m *TransactionReceipt) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TransactionReceipt.Marshal(b, m, deterministic)
}
func (m *TransactionReceipt) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TransactionReceipt.Merge(m, src)
}
func (m *TransactionReceipt) XXX_Size() int {
	return xxx_messageInfo_TransactionReceipt.Size(m)
}
func (m *TransactionReceipt) XXX_DiscardUnknown() {
	xxx_messageInfo_TransactionReceipt.DiscardUnknown(m)
}

var xxx_messageInfo_TransactionReceipt proto.InternalMessageInfo

func (m *TransactionReceipt) GetStatus() TransactionStatus {
	if m != nil {
		return m.Status
	}
	return TransactionStatus_UNKNOWN
}

func (m *TransactionReceipt) GetAccountID() *AccountID {
	if m != nil {
		return m.AccountID
	}
	return nil
}

func (m *TransactionReceipt) GetFileID() *FileID {
	if m != nil {
		return m.FileID
	}
	return nil
}

func (m *TransactionReceipt) GetContractID() *ContractID {
	if m != nil {
		return m.ContractID
	}
	return nil
}

func init() {
	proto.RegisterEnum("proto.TransactionStatus", TransactionStatus_name, TransactionStatus_value)
	proto.RegisterType((*TransactionReceipt)(nil), "proto.TransactionReceipt")
}

func init() { proto.RegisterFile("TransactionReceipt.proto", fileDescriptor_31337d5eb7330cd9) }

var fileDescriptor_31337d5eb7330cd9 = []byte{
	// 279 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x64, 0xce, 0xdf, 0x4a, 0xc3, 0x30,
	0x14, 0x06, 0x70, 0xb3, 0xcd, 0xa9, 0x67, 0x53, 0xb2, 0x5c, 0x15, 0xaf, 0xc6, 0x40, 0x19, 0x5e,
	0x14, 0x9d, 0x4f, 0xd0, 0xbf, 0x50, 0x2c, 0x55, 0xda, 0x4d, 0x2f, 0xc7, 0x31, 0x46, 0x5b, 0xd1,
	0xa6, 0x34, 0x99, 0xe0, 0x5b, 0xfa, 0x48, 0xb2, 0x2c, 0xce, 0xc1, 0xae, 0xc2, 0xf9, 0xbe, 0xdf,
	0x09, 0x07, 0x9c, 0x79, 0x8b, 0xb5, 0x42, 0xae, 0x2b, 0x59, 0xe7, 0x82, 0x8b, 0xaa, 0xd1, 0x6e,
	0xd3, 0x4a, 0x2d, 0xd9, 0xa1, 0x79, 0xce, 0xa9, 0x8f, 0xaa, 0xe2, 0xf3, 0xef, 0x46, 0xa8, 0x4d,
	0x31, 0xf9, 0x21, 0xc0, 0xf6, 0xb7, 0xd8, 0x35, 0xf4, 0x95, 0x46, 0xbd, 0x52, 0x0e, 0x19, 0x93,
	0xe9, 0xd9, 0xcc, 0xd9, 0x70, 0x77, 0x87, 0x16, 0xa6, 0xcf, 0xad, 0x63, 0x2e, 0x9c, 0x20, 0xe7,
	0x72, 0x55, 0xeb, 0x24, 0x74, 0x3a, 0x63, 0x32, 0x1d, 0xcc, 0xa8, 0x5d, 0xf2, 0xfe, 0xf2, 0xfc,
	0x9f, 0xb0, 0x0b, 0xe8, 0xbf, 0x56, 0x1f, 0x22, 0x09, 0x9d, 0xae, 0xc1, 0xa7, 0x16, 0xc7, 0x26,
	0xcc, 0x6d, 0xc9, 0x6e, 0x00, 0xb8, 0xac, 0x75, 0x8b, 0x7c, 0xfd, 0x6f, 0xcf, 0xd0, 0x91, 0xa5,
	0xc1, 0xb6, 0xc8, 0x77, 0xd0, 0xd5, 0x12, 0x46, 0x7b, 0x67, 0xb2, 0x01, 0x1c, 0x2d, 0xb2, 0xbb,
	0xec, 0xfe, 0x29, 0xa3, 0x07, 0xeb, 0xa1, 0x58, 0x04, 0x41, 0x54, 0x14, 0x94, 0x30, 0x0a, 0xc3,
	0xd8, 0x4b, 0xd2, 0x65, 0x92, 0x3d, 0x7a, 0x69, 0x12, 0xd2, 0x0e, 0x1b, 0xc2, 0xb1, 0x49, 0xe2,
	0x28, 0xa2, 0xdd, 0x6d, 0xef, 0x7b, 0xa9, 0x97, 0x05, 0x11, 0xed, 0xf9, 0x97, 0x30, 0xe1, 0xf2,
	0xd3, 0x2d, 0xc5, 0x8b, 0x68, 0xb1, 0x44, 0x55, 0xbe, 0xb5, 0xd8, 0x94, 0x2e, 0x36, 0x95, 0x3d,
	0xec, 0x1d, 0xbf, 0xf0, 0x81, 0x3c, 0xf7, 0xcd, 0x74, 0xfb, 0x1b, 0x00, 0x00, 0xff, 0xff, 0x59,
	0x7e, 0xbe, 0x52, 0x97, 0x01, 0x00, 0x00,
}
