// Code generated by protoc-gen-go. DO NOT EDIT.
// source: CryptoUpdate.proto

package proto

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

// Change properties for the given account. Any null field is ignored (left unchanged). The receiverSigRequired boolean field cannot be changed; it is immutable. This transaction must be signed by the existing key for this account. If the transaction is changing the key field, then the transaction must be signed by both the old key (from before the change) and the new key. The old key must sign for security. The new key must sign as a safeguard to avoid accidentally changing to an invalid key, and then having no way to recover. When extending the expiration date, the cost is affected by the size of the list of attached claims, and of the keys associated with the claims and the account.
type CryptoUpdateTransactionBody struct {
	AccountIDToUpdate      *AccountID `protobuf:"bytes,2,opt,name=accountIDToUpdate,proto3" json:"accountIDToUpdate,omitempty"`
	Key                    *Key       `protobuf:"bytes,3,opt,name=key,proto3" json:"key,omitempty"`
	ProxyAccountID         *AccountID `protobuf:"bytes,4,opt,name=proxyAccountID,proto3" json:"proxyAccountID,omitempty"`
	ProxyFraction          int32      `protobuf:"varint,5,opt,name=proxyFraction,proto3" json:"proxyFraction,omitempty"`
	SendRecordThreshold    uint64     `protobuf:"varint,6,opt,name=sendRecordThreshold,proto3" json:"sendRecordThreshold,omitempty"`
	ReceiveRecordThreshold uint64     `protobuf:"varint,7,opt,name=receiveRecordThreshold,proto3" json:"receiveRecordThreshold,omitempty"`
	AutoRenewPeriod        *Duration  `protobuf:"bytes,8,opt,name=autoRenewPeriod,proto3" json:"autoRenewPeriod,omitempty"`
	ExpirationTime         *Timestamp `protobuf:"bytes,9,opt,name=expirationTime,proto3" json:"expirationTime,omitempty"`
	XXX_NoUnkeyedLiteral   struct{}   `json:"-"`
	XXX_unrecognized       []byte     `json:"-"`
	XXX_sizecache          int32      `json:"-"`
}

func (m *CryptoUpdateTransactionBody) Reset()         { *m = CryptoUpdateTransactionBody{} }
func (m *CryptoUpdateTransactionBody) String() string { return proto.CompactTextString(m) }
func (*CryptoUpdateTransactionBody) ProtoMessage()    {}
func (*CryptoUpdateTransactionBody) Descriptor() ([]byte, []int) {
	return fileDescriptor_bb78671897dfb7d1, []int{0}
}

func (m *CryptoUpdateTransactionBody) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CryptoUpdateTransactionBody.Unmarshal(m, b)
}
func (m *CryptoUpdateTransactionBody) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CryptoUpdateTransactionBody.Marshal(b, m, deterministic)
}
func (m *CryptoUpdateTransactionBody) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CryptoUpdateTransactionBody.Merge(m, src)
}
func (m *CryptoUpdateTransactionBody) XXX_Size() int {
	return xxx_messageInfo_CryptoUpdateTransactionBody.Size(m)
}
func (m *CryptoUpdateTransactionBody) XXX_DiscardUnknown() {
	xxx_messageInfo_CryptoUpdateTransactionBody.DiscardUnknown(m)
}

var xxx_messageInfo_CryptoUpdateTransactionBody proto.InternalMessageInfo

func (m *CryptoUpdateTransactionBody) GetAccountIDToUpdate() *AccountID {
	if m != nil {
		return m.AccountIDToUpdate
	}
	return nil
}

func (m *CryptoUpdateTransactionBody) GetKey() *Key {
	if m != nil {
		return m.Key
	}
	return nil
}

func (m *CryptoUpdateTransactionBody) GetProxyAccountID() *AccountID {
	if m != nil {
		return m.ProxyAccountID
	}
	return nil
}

func (m *CryptoUpdateTransactionBody) GetProxyFraction() int32 {
	if m != nil {
		return m.ProxyFraction
	}
	return 0
}

func (m *CryptoUpdateTransactionBody) GetSendRecordThreshold() uint64 {
	if m != nil {
		return m.SendRecordThreshold
	}
	return 0
}

func (m *CryptoUpdateTransactionBody) GetReceiveRecordThreshold() uint64 {
	if m != nil {
		return m.ReceiveRecordThreshold
	}
	return 0
}

func (m *CryptoUpdateTransactionBody) GetAutoRenewPeriod() *Duration {
	if m != nil {
		return m.AutoRenewPeriod
	}
	return nil
}

func (m *CryptoUpdateTransactionBody) GetExpirationTime() *Timestamp {
	if m != nil {
		return m.ExpirationTime
	}
	return nil
}

func init() {
	proto.RegisterType((*CryptoUpdateTransactionBody)(nil), "proto.CryptoUpdateTransactionBody")
}

func init() { proto.RegisterFile("CryptoUpdate.proto", fileDescriptor_bb78671897dfb7d1) }

var fileDescriptor_bb78671897dfb7d1 = []byte{
	// 318 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x74, 0x51, 0x5d, 0x4b, 0xf3, 0x30,
	0x14, 0xa6, 0xef, 0x3e, 0x5e, 0x8d, 0xb8, 0xcd, 0x08, 0x12, 0xa6, 0x17, 0x63, 0x88, 0xec, 0xaa,
	0x88, 0x82, 0xe8, 0x8d, 0xe0, 0x1c, 0x82, 0x78, 0x33, 0x42, 0xfd, 0x01, 0xc7, 0xe4, 0x60, 0xa3,
	0xae, 0x09, 0x49, 0x36, 0xd7, 0xbf, 0xe6, 0xaf, 0x93, 0xa6, 0xdd, 0x70, 0xd5, 0x5d, 0x85, 0xf3,
	0x7c, 0x91, 0x73, 0x1e, 0x42, 0xef, 0x6d, 0x6e, 0xbc, 0x7e, 0x36, 0x12, 0x3c, 0xc6, 0xc6, 0x6a,
	0xaf, 0x69, 0x2b, 0x3c, 0xfd, 0xde, 0x18, 0x9c, 0x12, 0x49, 0x6e, 0xd0, 0x95, 0x44, 0xbf, 0x33,
	0x99, 0x5b, 0xf0, 0x4a, 0x67, 0xd5, 0xdc, 0x4d, 0xd4, 0x0c, 0x9d, 0x87, 0x99, 0x29, 0x81, 0xe1,
	0x57, 0x83, 0x1c, 0xff, 0x0c, 0x4c, 0x2c, 0x64, 0x0e, 0x44, 0x61, 0x19, 0x6b, 0x99, 0xd3, 0x5b,
	0x72, 0x00, 0x42, 0xe8, 0x79, 0xe6, 0x1f, 0x27, 0x49, 0xa5, 0x61, 0xff, 0x06, 0xd1, 0x68, 0xef,
	0xa2, 0x57, 0x46, 0xc4, 0x77, 0x2b, 0x9e, 0xff, 0x96, 0xd2, 0x13, 0xd2, 0x78, 0xc7, 0x9c, 0x35,
	0x82, 0x83, 0x54, 0x8e, 0x27, 0xcc, 0x79, 0x01, 0xd3, 0x6b, 0xd2, 0x31, 0x56, 0x2f, 0xf3, 0x75,
	0x04, 0x6b, 0x6e, 0x89, 0xae, 0xe9, 0xe8, 0x29, 0xd9, 0x0f, 0xc8, 0x83, 0x2d, 0x3f, 0xcb, 0x5a,
	0x83, 0x68, 0xd4, 0xe2, 0x9b, 0x20, 0x3d, 0x27, 0x87, 0x0e, 0x33, 0xc9, 0x51, 0x68, 0x2b, 0x93,
	0xd4, 0xa2, 0x4b, 0xf5, 0x87, 0x64, 0xed, 0x41, 0x34, 0x6a, 0xf2, 0xbf, 0x28, 0x7a, 0x45, 0x8e,
	0x2c, 0x0a, 0x54, 0x0b, 0xac, 0x9b, 0xfe, 0x07, 0xd3, 0x16, 0x96, 0xde, 0x90, 0x2e, 0xcc, 0xbd,
	0xe6, 0x98, 0xe1, 0xe7, 0x14, 0xad, 0xd2, 0x92, 0xed, 0x84, 0x55, 0xba, 0xd5, 0x2a, 0xab, 0x22,
	0x78, 0x5d, 0x57, 0x1c, 0x01, 0x97, 0x46, 0x95, 0x74, 0xd1, 0x0f, 0xdb, 0xdd, 0x38, 0xc2, 0xba,
	0x32, 0x5e, 0xd3, 0x8d, 0xcf, 0xc8, 0x50, 0xe8, 0x59, 0x9c, 0xa2, 0x44, 0x0b, 0x29, 0xb8, 0xf4,
	0xd5, 0x82, 0x49, 0x63, 0x30, 0xaa, 0xb2, 0xbe, 0xc1, 0x02, 0xa6, 0xd1, 0x4b, 0x3b, 0x4c, 0x97,
	0xdf, 0x01, 0x00, 0x00, 0xff, 0xff, 0xf8, 0x7f, 0x72, 0xe6, 0x3b, 0x02, 0x00, 0x00,
}
