// Code generated by protoc-gen-go. DO NOT EDIT.
// source: CryptoCreate.proto

package proto

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

// Create a new account. After the account is created, the AccountID for it is in the receipt, or can be retrieved with a GetByKey query, or by asking for a Record of the transaction to be created, and retrieving that. The account can then automatically generate records for large transfers into it or out of it, which each last for 24 hours. Records are generated for any transfer that exceeds the thresholds given here. This account is charged cryptocurrency for each record generated, so the thresholds are useful for limiting Record generation to happen only for large transactions. The Key field is the key used to sign transactions for this account. If the account has receiverSigRequired set to true, then all cryptocurrency transfers must be signed by this account's key, both for transfers in and out. If it is false, then only transfers out have to be signed by it. When the account is created, the payer account is charged enough hbars so that the new account will not expire for the next autoRenewPeriod seconds. When it reaches the expiration time, the new account will then be automatically charged to renew for another autoRenewPeriod seconds. If it does not have enough hbars to renew for that long, then the remaining hbars are used to extend its expiration as long as possible. If it is has a zero balance when it expires, then it is deleted. This transaction must be signed by the payer account. If receiverSigRequired is false, then the transaction does not have to be signed by the keys in the keys field. If it is true, then it must be signed by them, in addition to the keys of the payer account.
//
// An entity (account, file, or smart contract instance) must be created in a particular realm. If the realmID is left null, then a new realm will be created with the given admin key. If a new realm has a null adminKey, then anyone can create/modify/delete entities in that realm. But if an admin key is given, then any transaction to create/modify/delete an entity in that realm must be signed by that key, though anyone can still call functions on smart contract instances that exist in that realm. A realm ceases to exist when everything within it has expired and no longer exists.
//
// The current API ignores shardID, realmID, and newRealmAdminKey, and creates everything in shard 0 and realm 0, with a null key. Future versions of the API will support multiple realms and multiple shards.
type CryptoCreateTransactionBody struct {
	Key                     *Key       `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	InitialBalance          uint64     `protobuf:"varint,2,opt,name=initialBalance,proto3" json:"initialBalance,omitempty"`
	ProxyAccountID          *AccountID `protobuf:"bytes,3,opt,name=proxyAccountID,proto3" json:"proxyAccountID,omitempty"`
	ProxyFraction           int32      `protobuf:"varint,4,opt,name=proxyFraction,proto3" json:"proxyFraction,omitempty"`
	MaxReceiveProxyFraction int32      `protobuf:"varint,5,opt,name=maxReceiveProxyFraction,proto3" json:"maxReceiveProxyFraction,omitempty"`
	SendRecordThreshold     uint64     `protobuf:"varint,6,opt,name=sendRecordThreshold,proto3" json:"sendRecordThreshold,omitempty"`
	ReceiveRecordThreshold  uint64     `protobuf:"varint,7,opt,name=receiveRecordThreshold,proto3" json:"receiveRecordThreshold,omitempty"`
	ReceiverSigRequired     bool       `protobuf:"varint,8,opt,name=receiverSigRequired,proto3" json:"receiverSigRequired,omitempty"`
	AutoRenewPeriod         *Duration  `protobuf:"bytes,9,opt,name=autoRenewPeriod,proto3" json:"autoRenewPeriod,omitempty"`
	ShardID                 *ShardID   `protobuf:"bytes,10,opt,name=shardID,proto3" json:"shardID,omitempty"`
	RealmID                 *RealmID   `protobuf:"bytes,11,opt,name=realmID,proto3" json:"realmID,omitempty"`
	NewRealmAdminKey        *Key       `protobuf:"bytes,12,opt,name=newRealmAdminKey,proto3" json:"newRealmAdminKey,omitempty"`
	XXX_NoUnkeyedLiteral    struct{}   `json:"-"`
	XXX_unrecognized        []byte     `json:"-"`
	XXX_sizecache           int32      `json:"-"`
}

func (m *CryptoCreateTransactionBody) Reset()         { *m = CryptoCreateTransactionBody{} }
func (m *CryptoCreateTransactionBody) String() string { return proto.CompactTextString(m) }
func (*CryptoCreateTransactionBody) ProtoMessage()    {}
func (*CryptoCreateTransactionBody) Descriptor() ([]byte, []int) {
	return fileDescriptor_89b414cfdad72647, []int{0}
}

func (m *CryptoCreateTransactionBody) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CryptoCreateTransactionBody.Unmarshal(m, b)
}
func (m *CryptoCreateTransactionBody) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CryptoCreateTransactionBody.Marshal(b, m, deterministic)
}
func (m *CryptoCreateTransactionBody) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CryptoCreateTransactionBody.Merge(m, src)
}
func (m *CryptoCreateTransactionBody) XXX_Size() int {
	return xxx_messageInfo_CryptoCreateTransactionBody.Size(m)
}
func (m *CryptoCreateTransactionBody) XXX_DiscardUnknown() {
	xxx_messageInfo_CryptoCreateTransactionBody.DiscardUnknown(m)
}

var xxx_messageInfo_CryptoCreateTransactionBody proto.InternalMessageInfo

func (m *CryptoCreateTransactionBody) GetKey() *Key {
	if m != nil {
		return m.Key
	}
	return nil
}

func (m *CryptoCreateTransactionBody) GetInitialBalance() uint64 {
	if m != nil {
		return m.InitialBalance
	}
	return 0
}

func (m *CryptoCreateTransactionBody) GetProxyAccountID() *AccountID {
	if m != nil {
		return m.ProxyAccountID
	}
	return nil
}

func (m *CryptoCreateTransactionBody) GetProxyFraction() int32 {
	if m != nil {
		return m.ProxyFraction
	}
	return 0
}

func (m *CryptoCreateTransactionBody) GetMaxReceiveProxyFraction() int32 {
	if m != nil {
		return m.MaxReceiveProxyFraction
	}
	return 0
}

func (m *CryptoCreateTransactionBody) GetSendRecordThreshold() uint64 {
	if m != nil {
		return m.SendRecordThreshold
	}
	return 0
}

func (m *CryptoCreateTransactionBody) GetReceiveRecordThreshold() uint64 {
	if m != nil {
		return m.ReceiveRecordThreshold
	}
	return 0
}

func (m *CryptoCreateTransactionBody) GetReceiverSigRequired() bool {
	if m != nil {
		return m.ReceiverSigRequired
	}
	return false
}

func (m *CryptoCreateTransactionBody) GetAutoRenewPeriod() *Duration {
	if m != nil {
		return m.AutoRenewPeriod
	}
	return nil
}

func (m *CryptoCreateTransactionBody) GetShardID() *ShardID {
	if m != nil {
		return m.ShardID
	}
	return nil
}

func (m *CryptoCreateTransactionBody) GetRealmID() *RealmID {
	if m != nil {
		return m.RealmID
	}
	return nil
}

func (m *CryptoCreateTransactionBody) GetNewRealmAdminKey() *Key {
	if m != nil {
		return m.NewRealmAdminKey
	}
	return nil
}

func init() {
	proto.RegisterType((*CryptoCreateTransactionBody)(nil), "proto.CryptoCreateTransactionBody")
}

func init() { proto.RegisterFile("CryptoCreate.proto", fileDescriptor_89b414cfdad72647) }

var fileDescriptor_89b414cfdad72647 = []byte{
	// 387 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x74, 0x92, 0xd1, 0x6a, 0x9c, 0x40,
	0x14, 0x86, 0xb1, 0xd9, 0x4d, 0xd2, 0x49, 0x6b, 0x96, 0x29, 0xb4, 0x43, 0xda, 0x0b, 0x09, 0x25,
	0x78, 0x25, 0xa5, 0x85, 0x90, 0x5e, 0xc6, 0x48, 0x61, 0xc9, 0xcd, 0x32, 0xd9, 0x17, 0x38, 0x9d,
	0x39, 0xc4, 0x69, 0x75, 0xc6, 0x1e, 0x35, 0x89, 0x6f, 0xdb, 0x47, 0x29, 0x8e, 0x6e, 0xc9, 0x9a,
	0xdd, 0x2b, 0x99, 0xff, 0xfb, 0xfe, 0xa3, 0x1e, 0x65, 0xfc, 0x86, 0xba, 0xaa, 0x71, 0x37, 0x84,
	0xd0, 0x60, 0x52, 0x91, 0x6b, 0x1c, 0x9f, 0xfb, 0xcb, 0xd9, 0x22, 0x85, 0xda, 0xa8, 0x75, 0x57,
	0x61, 0x3d, 0x80, 0xb3, 0x30, 0x6b, 0x09, 0x1a, 0xe3, 0xec, 0x70, 0x3e, 0xff, 0x3b, 0x63, 0x1f,
	0x9f, 0xf7, 0xd7, 0x04, 0xb6, 0x06, 0xd5, 0x1b, 0xa9, 0xd3, 0x1d, 0xff, 0xc4, 0x0e, 0x7e, 0x63,
	0x27, 0x82, 0x28, 0x88, 0x4f, 0xbe, 0xb2, 0xa1, 0x94, 0xdc, 0x62, 0x27, 0xfb, 0x98, 0x5f, 0xb0,
	0xd0, 0x58, 0xd3, 0x18, 0x28, 0x52, 0x28, 0xc0, 0x2a, 0x14, 0xaf, 0xa2, 0x20, 0x9e, 0xc9, 0x49,
	0xca, 0xaf, 0x58, 0x58, 0x91, 0x7b, 0xea, 0xae, 0x95, 0x72, 0xad, 0x6d, 0x96, 0x99, 0x38, 0xf0,
	0x03, 0x17, 0xe3, 0xc0, 0xff, 0xb9, 0x9c, 0x78, 0xfc, 0x33, 0x7b, 0xeb, 0x93, 0x1f, 0x34, 0x3c,
	0x94, 0x98, 0x45, 0x41, 0x3c, 0x97, 0xdb, 0x21, 0xbf, 0x62, 0x1f, 0x4a, 0x78, 0x92, 0xa8, 0xd0,
	0x3c, 0xe0, 0x6a, 0xcb, 0x9f, 0x7b, 0x7f, 0x1f, 0xe6, 0x5f, 0xd8, 0xbb, 0x1a, 0xad, 0x96, 0xa8,
	0x1c, 0xe9, 0x75, 0x4e, 0x58, 0xe7, 0xae, 0xd0, 0xe2, 0xd0, 0xbf, 0xc6, 0x2e, 0xc4, 0x2f, 0xd9,
	0x7b, 0x1a, 0x26, 0x4d, 0x4b, 0x47, 0xbe, 0xb4, 0x87, 0xf6, 0x77, 0x1a, 0x09, 0xdd, 0x99, 0x7b,
	0x89, 0x7f, 0x5a, 0x43, 0xa8, 0xc5, 0x71, 0x14, 0xc4, 0xc7, 0x72, 0x17, 0xe2, 0xdf, 0xd9, 0x29,
	0xb4, 0x8d, 0x93, 0x68, 0xf1, 0x71, 0x85, 0x64, 0x9c, 0x16, 0xaf, 0xfd, 0xda, 0x4e, 0xc7, 0xb5,
	0x6d, 0xbe, 0xa5, 0x9c, 0x7a, 0x3c, 0x66, 0x47, 0x75, 0x0e, 0xa4, 0x97, 0x99, 0x60, 0xbe, 0x12,
	0x8e, 0x95, 0xbb, 0x21, 0x95, 0x1b, 0xdc, 0x9b, 0x84, 0x50, 0x94, 0xcb, 0x4c, 0x9c, 0x6c, 0x99,
	0x72, 0x48, 0xe5, 0x06, 0xf3, 0x4b, 0xb6, 0xb0, 0xf8, 0xe8, 0xe3, 0x6b, 0x5d, 0x1a, 0x7b, 0x8b,
	0x9d, 0x78, 0xf3, 0xe2, 0xbf, 0x78, 0xe1, 0xa4, 0x17, 0xec, 0x5c, 0xb9, 0x32, 0xc9, 0x51, 0x23,
	0x41, 0x0e, 0x75, 0x7e, 0x4f, 0x50, 0xe5, 0x09, 0x54, 0x66, 0xac, 0xfd, 0x82, 0x07, 0x58, 0x05,
	0x3f, 0x0f, 0xfd, 0xe9, 0xdb, 0xbf, 0x00, 0x00, 0x00, 0xff, 0xff, 0xf6, 0xea, 0x0b, 0xca, 0xd0,
	0x02, 0x00, 0x00,
}
