// Code generated by protoc-gen-go. DO NOT EDIT.
// source: CryptoAddClaim.proto

package proto

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

// A hash (presumably of some kind of credential or certificate), along with a list  of threshold keys. Each of them must reach its threshold when signing the transaction, to attach this claim to this account. At least one of them must reach its threshold to delete this Claim from this account. This is intended to provide a revocation service: all the authorities agree to attach the hash, to attest to the fact that the credential or certificate is valid. Any one of the authorities can later delete the hash, to indicate that the credential has been revoked. In this way, any client can prove to a third party that any particular account has certain credentials, or to identity facts proved about it, and that none of them have been revoked yet.
type Claim struct {
	AccountID            *AccountID `protobuf:"bytes,1,opt,name=accountID,proto3" json:"accountID,omitempty"`
	Hash                 []byte     `protobuf:"bytes,2,opt,name=hash,proto3" json:"hash,omitempty"`
	Keys                 *KeyList   `protobuf:"bytes,3,opt,name=keys,proto3" json:"keys,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *Claim) Reset()         { *m = Claim{} }
func (m *Claim) String() string { return proto.CompactTextString(m) }
func (*Claim) ProtoMessage()    {}
func (*Claim) Descriptor() ([]byte, []int) {
	return fileDescriptor_ec938addb78951d5, []int{0}
}

func (m *Claim) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Claim.Unmarshal(m, b)
}
func (m *Claim) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Claim.Marshal(b, m, deterministic)
}
func (m *Claim) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Claim.Merge(m, src)
}
func (m *Claim) XXX_Size() int {
	return xxx_messageInfo_Claim.Size(m)
}
func (m *Claim) XXX_DiscardUnknown() {
	xxx_messageInfo_Claim.DiscardUnknown(m)
}

var xxx_messageInfo_Claim proto.InternalMessageInfo

func (m *Claim) GetAccountID() *AccountID {
	if m != nil {
		return m.AccountID
	}
	return nil
}

func (m *Claim) GetHash() []byte {
	if m != nil {
		return m.Hash
	}
	return nil
}

func (m *Claim) GetKeys() *KeyList {
	if m != nil {
		return m.Keys
	}
	return nil
}

// Attach the given hash to the given account. The hash can be deleted by the keys used to transfer money from the account. The hash can also be deleted by any one of the deleteKeys (where that one may itself be a threshold key made up of multiple keys). Therefore, this acts as a revocation service for claims about the account. External authorities may issue certificates or credentials of some kind that make a claim about this account. The account owner can then attach a hash of that claim to the account. The transaction that adds the claim will be signed by the owner of the account, and also by all the authorities that are attesting to the truth of that claim. If the claim ever ceases to be true, such as when a certificate is revoked, then any one of the listed authorities has the ability to delete it. The account owner also has the ability to delete it at any time.
//
// In this way, it acts as a revocation server, and the account owner can prove to any third party that the claim is still true for this account, by sending the third party the signed credential, and then having the third party query to discover whether the hash of that credential is still attached to the account.
//
// For a given account, each Claim must contain a different hash. To modify the list of keys in a Claim, the existing Claim should first be deleted, then the Claim with the new list of keys can be added.
type CryptoAddClaimTransactionBody struct {
	AccountID            *AccountID `protobuf:"bytes,2,opt,name=accountID,proto3" json:"accountID,omitempty"`
	Claim                *Claim     `protobuf:"bytes,3,opt,name=claim,proto3" json:"claim,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *CryptoAddClaimTransactionBody) Reset()         { *m = CryptoAddClaimTransactionBody{} }
func (m *CryptoAddClaimTransactionBody) String() string { return proto.CompactTextString(m) }
func (*CryptoAddClaimTransactionBody) ProtoMessage()    {}
func (*CryptoAddClaimTransactionBody) Descriptor() ([]byte, []int) {
	return fileDescriptor_ec938addb78951d5, []int{1}
}

func (m *CryptoAddClaimTransactionBody) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CryptoAddClaimTransactionBody.Unmarshal(m, b)
}
func (m *CryptoAddClaimTransactionBody) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CryptoAddClaimTransactionBody.Marshal(b, m, deterministic)
}
func (m *CryptoAddClaimTransactionBody) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CryptoAddClaimTransactionBody.Merge(m, src)
}
func (m *CryptoAddClaimTransactionBody) XXX_Size() int {
	return xxx_messageInfo_CryptoAddClaimTransactionBody.Size(m)
}
func (m *CryptoAddClaimTransactionBody) XXX_DiscardUnknown() {
	xxx_messageInfo_CryptoAddClaimTransactionBody.DiscardUnknown(m)
}

var xxx_messageInfo_CryptoAddClaimTransactionBody proto.InternalMessageInfo

func (m *CryptoAddClaimTransactionBody) GetAccountID() *AccountID {
	if m != nil {
		return m.AccountID
	}
	return nil
}

func (m *CryptoAddClaimTransactionBody) GetClaim() *Claim {
	if m != nil {
		return m.Claim
	}
	return nil
}

func init() {
	proto.RegisterType((*Claim)(nil), "proto.Claim")
	proto.RegisterType((*CryptoAddClaimTransactionBody)(nil), "proto.CryptoAddClaimTransactionBody")
}

func init() { proto.RegisterFile("CryptoAddClaim.proto", fileDescriptor_ec938addb78951d5) }

var fileDescriptor_ec938addb78951d5 = []byte{
	// 221 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x84, 0x8e, 0xcf, 0x4a, 0x03, 0x31,
	0x10, 0xc6, 0x49, 0xed, 0x0a, 0x8e, 0x45, 0x4a, 0xf0, 0xb0, 0x08, 0x42, 0xc9, 0x41, 0x7a, 0xca,
	0x41, 0x9f, 0xa0, 0x5b, 0x2f, 0xa2, 0x07, 0x09, 0x7d, 0x81, 0x31, 0x09, 0x26, 0x6a, 0x77, 0x42,
	0x12, 0x85, 0xbc, 0xbd, 0x34, 0x1b, 0x91, 0x9e, 0x7a, 0xca, 0x9f, 0xef, 0x37, 0xdf, 0xfc, 0xe0,
	0x7a, 0x1b, 0x4b, 0xc8, 0xb4, 0x31, 0x66, 0xfb, 0x85, 0x7e, 0x2f, 0x43, 0xa4, 0x4c, 0xbc, 0xab,
	0xc7, 0xcd, 0x72, 0xc0, 0xe4, 0xf5, 0xae, 0x04, 0x9b, 0xa6, 0x40, 0x10, 0x74, 0x95, 0xe3, 0x12,
	0x2e, 0x50, 0x6b, 0xfa, 0x1e, 0xf3, 0xd3, 0x63, 0xcf, 0x56, 0x6c, 0x7d, 0x79, 0xbf, 0x9c, 0x18,
	0xb9, 0xf9, 0xfb, 0x57, 0xff, 0x08, 0xe7, 0x30, 0x77, 0x98, 0x5c, 0x3f, 0x5b, 0xb1, 0xf5, 0x42,
	0xd5, 0x3b, 0x17, 0x30, 0xff, 0xb4, 0x25, 0xf5, 0x67, 0x75, 0xfc, 0xaa, 0x8d, 0x3f, 0xdb, 0xf2,
	0xe2, 0x53, 0x56, 0x35, 0x13, 0x09, 0x6e, 0x8f, 0x0d, 0x77, 0x11, 0xc7, 0x84, 0x3a, 0x7b, 0x1a,
	0x07, 0x32, 0xe5, 0x58, 0x64, 0x76, 0x5a, 0x44, 0x40, 0xa7, 0x0f, 0x3d, 0x6d, 0xeb, 0xa2, 0xb1,
	0xb5, 0x5b, 0x4d, 0xd1, 0x70, 0x07, 0x42, 0xd3, 0x5e, 0x3a, 0x6b, 0x6c, 0xc4, 0x83, 0xea, 0x7b,
	0xc4, 0xe0, 0x24, 0x06, 0xdf, 0xe8, 0x0f, 0xfc, 0xc1, 0x57, 0xf6, 0x76, 0x5e, 0x5f, 0x0f, 0xbf,
	0x01, 0x00, 0x00, 0xff, 0xff, 0x24, 0x18, 0x79, 0xaa, 0x45, 0x01, 0x00, 0x00,
}
