// Code generated by protoc-gen-go. DO NOT EDIT.
// source: CreateFeeSchedule.proto

package proto

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type CreateFeeScheduleTransactionBody struct {
	Key                    *Key                      `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	TransactionFeeSchedule []*TransactionFeeSchedule `protobuf:"bytes,2,rep,name=transactionFeeSchedule,proto3" json:"transactionFeeSchedule,omitempty"`
	XXX_NoUnkeyedLiteral   struct{}                  `json:"-"`
	XXX_unrecognized       []byte                    `json:"-"`
	XXX_sizecache          int32                     `json:"-"`
}

func (m *CreateFeeScheduleTransactionBody) Reset()         { *m = CreateFeeScheduleTransactionBody{} }
func (m *CreateFeeScheduleTransactionBody) String() string { return proto.CompactTextString(m) }
func (*CreateFeeScheduleTransactionBody) ProtoMessage()    {}
func (*CreateFeeScheduleTransactionBody) Descriptor() ([]byte, []int) {
	return fileDescriptor_2e73f9544b428849, []int{0}
}

func (m *CreateFeeScheduleTransactionBody) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateFeeScheduleTransactionBody.Unmarshal(m, b)
}
func (m *CreateFeeScheduleTransactionBody) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateFeeScheduleTransactionBody.Marshal(b, m, deterministic)
}
func (m *CreateFeeScheduleTransactionBody) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateFeeScheduleTransactionBody.Merge(m, src)
}
func (m *CreateFeeScheduleTransactionBody) XXX_Size() int {
	return xxx_messageInfo_CreateFeeScheduleTransactionBody.Size(m)
}
func (m *CreateFeeScheduleTransactionBody) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateFeeScheduleTransactionBody.DiscardUnknown(m)
}

var xxx_messageInfo_CreateFeeScheduleTransactionBody proto.InternalMessageInfo

func (m *CreateFeeScheduleTransactionBody) GetKey() *Key {
	if m != nil {
		return m.Key
	}
	return nil
}

func (m *CreateFeeScheduleTransactionBody) GetTransactionFeeSchedule() []*TransactionFeeSchedule {
	if m != nil {
		return m.TransactionFeeSchedule
	}
	return nil
}

func init() {
	proto.RegisterType((*CreateFeeScheduleTransactionBody)(nil), "proto.CreateFeeScheduleTransactionBody")
}

func init() { proto.RegisterFile("CreateFeeSchedule.proto", fileDescriptor_2e73f9544b428849) }

var fileDescriptor_2e73f9544b428849 = []byte{
	// 178 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0x12, 0x77, 0x2e, 0x4a, 0x4d,
	0x2c, 0x49, 0x75, 0x4b, 0x4d, 0x0d, 0x4e, 0xce, 0x48, 0x4d, 0x29, 0xcd, 0x49, 0xd5, 0x2b, 0x28,
	0xca, 0x2f, 0xc9, 0x17, 0x62, 0x05, 0x53, 0x52, 0x02, 0x4e, 0x89, 0xc5, 0x99, 0xc9, 0x21, 0x95,
	0x05, 0xa9, 0xc5, 0x10, 0x09, 0xa5, 0xe9, 0x8c, 0x5c, 0x0a, 0x18, 0x9a, 0x42, 0x8a, 0x12, 0xf3,
	0x8a, 0x13, 0x93, 0x4b, 0x32, 0xf3, 0xf3, 0x9c, 0xf2, 0x53, 0x2a, 0x85, 0x64, 0xb8, 0x98, 0xb3,
	0x53, 0x2b, 0x25, 0x18, 0x15, 0x18, 0x35, 0xb8, 0x8d, 0xb8, 0x20, 0x3a, 0xf5, 0xbc, 0x53, 0x2b,
	0x83, 0x40, 0xc2, 0x42, 0xa1, 0x5c, 0x62, 0x25, 0x08, 0x0d, 0x48, 0xc6, 0x48, 0x30, 0x29, 0x30,
	0x6b, 0x70, 0x1b, 0xc9, 0x42, 0x35, 0x84, 0x60, 0x55, 0x14, 0x84, 0x43, 0xb3, 0x93, 0x1a, 0x97,
	0x52, 0x72, 0x7e, 0xae, 0x5e, 0x46, 0x6a, 0x4a, 0x6a, 0x51, 0x62, 0x46, 0x62, 0x71, 0x46, 0x7a,
	0x51, 0x62, 0x41, 0x86, 0x5e, 0x62, 0x41, 0x26, 0xd4, 0xbc, 0xac, 0xc4, 0xb2, 0xc4, 0x00, 0xc6,
	0x24, 0x36, 0x30, 0xcf, 0x18, 0x10, 0x00, 0x00, 0xff, 0xff, 0x8e, 0xd6, 0x1e, 0x94, 0xfc, 0x00,
	0x00, 0x00,
}
