// Code generated by protoc-gen-go. DO NOT EDIT.
// source: Query.proto

package proto

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

// A single query, which is sent from the client to the node. This includes all possible queries.
type Query struct {
	// Types that are valid to be assigned to Query:
	//	*Query_GetByKey
	//	*Query_GetBySolidityID
	//	*Query_ContractCallLocal
	//	*Query_ContractGetInfo
	//	*Query_ContractGetBytecode
	//	*Query_ContractGetRecords
	//	*Query_CryptogetAccountBalance
	//	*Query_CryptoGetAccountRecords
	//	*Query_CryptoGetInfo
	//	*Query_CryptoGetClaim
	//	*Query_CryptoGetProxyStakers
	//	*Query_FileGetContents
	//	*Query_FileGetInfo
	//	*Query_TransactionGetReceipt
	//	*Query_TransactionGetRecord
	Query                isQuery_Query `protobuf_oneof:"query"`
	XXX_NoUnkeyedLiteral struct{}      `json:"-"`
	XXX_unrecognized     []byte        `json:"-"`
	XXX_sizecache        int32         `json:"-"`
}

func (m *Query) Reset()         { *m = Query{} }
func (m *Query) String() string { return proto.CompactTextString(m) }
func (*Query) ProtoMessage()    {}
func (*Query) Descriptor() ([]byte, []int) {
	return fileDescriptor_12565a3f476cd53f, []int{0}
}

func (m *Query) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Query.Unmarshal(m, b)
}
func (m *Query) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Query.Marshal(b, m, deterministic)
}
func (m *Query) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Query.Merge(m, src)
}
func (m *Query) XXX_Size() int {
	return xxx_messageInfo_Query.Size(m)
}
func (m *Query) XXX_DiscardUnknown() {
	xxx_messageInfo_Query.DiscardUnknown(m)
}

var xxx_messageInfo_Query proto.InternalMessageInfo

type isQuery_Query interface {
	isQuery_Query()
}

type Query_GetByKey struct {
	GetByKey *GetByKeyQuery `protobuf:"bytes,1,opt,name=getByKey,proto3,oneof"`
}

type Query_GetBySolidityID struct {
	GetBySolidityID *GetBySolidityIDQuery `protobuf:"bytes,2,opt,name=getBySolidityID,proto3,oneof"`
}

type Query_ContractCallLocal struct {
	ContractCallLocal *ContractCallLocalQuery `protobuf:"bytes,3,opt,name=contractCallLocal,proto3,oneof"`
}

type Query_ContractGetInfo struct {
	ContractGetInfo *ContractGetInfoQuery `protobuf:"bytes,4,opt,name=contractGetInfo,proto3,oneof"`
}

type Query_ContractGetBytecode struct {
	ContractGetBytecode *ContractGetBytecodeQuery `protobuf:"bytes,5,opt,name=contractGetBytecode,proto3,oneof"`
}

type Query_ContractGetRecords struct {
	ContractGetRecords *ContractGetRecordsQuery `protobuf:"bytes,6,opt,name=ContractGetRecords,proto3,oneof"`
}

type Query_CryptogetAccountBalance struct {
	CryptogetAccountBalance *CryptoGetAccountBalanceQuery `protobuf:"bytes,7,opt,name=cryptogetAccountBalance,proto3,oneof"`
}

type Query_CryptoGetAccountRecords struct {
	CryptoGetAccountRecords *CryptoGetAccountRecordsQuery `protobuf:"bytes,8,opt,name=cryptoGetAccountRecords,proto3,oneof"`
}

type Query_CryptoGetInfo struct {
	CryptoGetInfo *CryptoGetInfoQuery `protobuf:"bytes,9,opt,name=cryptoGetInfo,proto3,oneof"`
}

type Query_CryptoGetClaim struct {
	CryptoGetClaim *CryptoGetClaimQuery `protobuf:"bytes,10,opt,name=cryptoGetClaim,proto3,oneof"`
}

type Query_CryptoGetProxyStakers struct {
	CryptoGetProxyStakers *CryptoGetStakersQuery `protobuf:"bytes,11,opt,name=cryptoGetProxyStakers,proto3,oneof"`
}

type Query_FileGetContents struct {
	FileGetContents *FileGetContentsQuery `protobuf:"bytes,12,opt,name=fileGetContents,proto3,oneof"`
}

type Query_FileGetInfo struct {
	FileGetInfo *FileGetInfoQuery `protobuf:"bytes,13,opt,name=fileGetInfo,proto3,oneof"`
}

type Query_TransactionGetReceipt struct {
	TransactionGetReceipt *TransactionGetReceiptQuery `protobuf:"bytes,14,opt,name=transactionGetReceipt,proto3,oneof"`
}

type Query_TransactionGetRecord struct {
	TransactionGetRecord *TransactionGetRecordQuery `protobuf:"bytes,15,opt,name=transactionGetRecord,proto3,oneof"`
}

func (*Query_GetByKey) isQuery_Query() {}

func (*Query_GetBySolidityID) isQuery_Query() {}

func (*Query_ContractCallLocal) isQuery_Query() {}

func (*Query_ContractGetInfo) isQuery_Query() {}

func (*Query_ContractGetBytecode) isQuery_Query() {}

func (*Query_ContractGetRecords) isQuery_Query() {}

func (*Query_CryptogetAccountBalance) isQuery_Query() {}

func (*Query_CryptoGetAccountRecords) isQuery_Query() {}

func (*Query_CryptoGetInfo) isQuery_Query() {}

func (*Query_CryptoGetClaim) isQuery_Query() {}

func (*Query_CryptoGetProxyStakers) isQuery_Query() {}

func (*Query_FileGetContents) isQuery_Query() {}

func (*Query_FileGetInfo) isQuery_Query() {}

func (*Query_TransactionGetReceipt) isQuery_Query() {}

func (*Query_TransactionGetRecord) isQuery_Query() {}

func (m *Query) GetQuery() isQuery_Query {
	if m != nil {
		return m.Query
	}
	return nil
}

func (m *Query) GetGetByKey() *GetByKeyQuery {
	if x, ok := m.GetQuery().(*Query_GetByKey); ok {
		return x.GetByKey
	}
	return nil
}

func (m *Query) GetGetBySolidityID() *GetBySolidityIDQuery {
	if x, ok := m.GetQuery().(*Query_GetBySolidityID); ok {
		return x.GetBySolidityID
	}
	return nil
}

func (m *Query) GetContractCallLocal() *ContractCallLocalQuery {
	if x, ok := m.GetQuery().(*Query_ContractCallLocal); ok {
		return x.ContractCallLocal
	}
	return nil
}

func (m *Query) GetContractGetInfo() *ContractGetInfoQuery {
	if x, ok := m.GetQuery().(*Query_ContractGetInfo); ok {
		return x.ContractGetInfo
	}
	return nil
}

func (m *Query) GetContractGetBytecode() *ContractGetBytecodeQuery {
	if x, ok := m.GetQuery().(*Query_ContractGetBytecode); ok {
		return x.ContractGetBytecode
	}
	return nil
}

func (m *Query) GetContractGetRecords() *ContractGetRecordsQuery {
	if x, ok := m.GetQuery().(*Query_ContractGetRecords); ok {
		return x.ContractGetRecords
	}
	return nil
}

func (m *Query) GetCryptogetAccountBalance() *CryptoGetAccountBalanceQuery {
	if x, ok := m.GetQuery().(*Query_CryptogetAccountBalance); ok {
		return x.CryptogetAccountBalance
	}
	return nil
}

func (m *Query) GetCryptoGetAccountRecords() *CryptoGetAccountRecordsQuery {
	if x, ok := m.GetQuery().(*Query_CryptoGetAccountRecords); ok {
		return x.CryptoGetAccountRecords
	}
	return nil
}

func (m *Query) GetCryptoGetInfo() *CryptoGetInfoQuery {
	if x, ok := m.GetQuery().(*Query_CryptoGetInfo); ok {
		return x.CryptoGetInfo
	}
	return nil
}

func (m *Query) GetCryptoGetClaim() *CryptoGetClaimQuery {
	if x, ok := m.GetQuery().(*Query_CryptoGetClaim); ok {
		return x.CryptoGetClaim
	}
	return nil
}

func (m *Query) GetCryptoGetProxyStakers() *CryptoGetStakersQuery {
	if x, ok := m.GetQuery().(*Query_CryptoGetProxyStakers); ok {
		return x.CryptoGetProxyStakers
	}
	return nil
}

func (m *Query) GetFileGetContents() *FileGetContentsQuery {
	if x, ok := m.GetQuery().(*Query_FileGetContents); ok {
		return x.FileGetContents
	}
	return nil
}

func (m *Query) GetFileGetInfo() *FileGetInfoQuery {
	if x, ok := m.GetQuery().(*Query_FileGetInfo); ok {
		return x.FileGetInfo
	}
	return nil
}

func (m *Query) GetTransactionGetReceipt() *TransactionGetReceiptQuery {
	if x, ok := m.GetQuery().(*Query_TransactionGetReceipt); ok {
		return x.TransactionGetReceipt
	}
	return nil
}

func (m *Query) GetTransactionGetRecord() *TransactionGetRecordQuery {
	if x, ok := m.GetQuery().(*Query_TransactionGetRecord); ok {
		return x.TransactionGetRecord
	}
	return nil
}

// XXX_OneofFuncs is for the internal use of the proto package.
func (*Query) XXX_OneofFuncs() (func(msg proto.Message, b *proto.Buffer) error, func(msg proto.Message, tag, wire int, b *proto.Buffer) (bool, error), func(msg proto.Message) (n int), []interface{}) {
	return _Query_OneofMarshaler, _Query_OneofUnmarshaler, _Query_OneofSizer, []interface{}{
		(*Query_GetByKey)(nil),
		(*Query_GetBySolidityID)(nil),
		(*Query_ContractCallLocal)(nil),
		(*Query_ContractGetInfo)(nil),
		(*Query_ContractGetBytecode)(nil),
		(*Query_ContractGetRecords)(nil),
		(*Query_CryptogetAccountBalance)(nil),
		(*Query_CryptoGetAccountRecords)(nil),
		(*Query_CryptoGetInfo)(nil),
		(*Query_CryptoGetClaim)(nil),
		(*Query_CryptoGetProxyStakers)(nil),
		(*Query_FileGetContents)(nil),
		(*Query_FileGetInfo)(nil),
		(*Query_TransactionGetReceipt)(nil),
		(*Query_TransactionGetRecord)(nil),
	}
}

func _Query_OneofMarshaler(msg proto.Message, b *proto.Buffer) error {
	m := msg.(*Query)
	// query
	switch x := m.Query.(type) {
	case *Query_GetByKey:
		b.EncodeVarint(1<<3 | proto.WireBytes)
		if err := b.EncodeMessage(x.GetByKey); err != nil {
			return err
		}
	case *Query_GetBySolidityID:
		b.EncodeVarint(2<<3 | proto.WireBytes)
		if err := b.EncodeMessage(x.GetBySolidityID); err != nil {
			return err
		}
	case *Query_ContractCallLocal:
		b.EncodeVarint(3<<3 | proto.WireBytes)
		if err := b.EncodeMessage(x.ContractCallLocal); err != nil {
			return err
		}
	case *Query_ContractGetInfo:
		b.EncodeVarint(4<<3 | proto.WireBytes)
		if err := b.EncodeMessage(x.ContractGetInfo); err != nil {
			return err
		}
	case *Query_ContractGetBytecode:
		b.EncodeVarint(5<<3 | proto.WireBytes)
		if err := b.EncodeMessage(x.ContractGetBytecode); err != nil {
			return err
		}
	case *Query_ContractGetRecords:
		b.EncodeVarint(6<<3 | proto.WireBytes)
		if err := b.EncodeMessage(x.ContractGetRecords); err != nil {
			return err
		}
	case *Query_CryptogetAccountBalance:
		b.EncodeVarint(7<<3 | proto.WireBytes)
		if err := b.EncodeMessage(x.CryptogetAccountBalance); err != nil {
			return err
		}
	case *Query_CryptoGetAccountRecords:
		b.EncodeVarint(8<<3 | proto.WireBytes)
		if err := b.EncodeMessage(x.CryptoGetAccountRecords); err != nil {
			return err
		}
	case *Query_CryptoGetInfo:
		b.EncodeVarint(9<<3 | proto.WireBytes)
		if err := b.EncodeMessage(x.CryptoGetInfo); err != nil {
			return err
		}
	case *Query_CryptoGetClaim:
		b.EncodeVarint(10<<3 | proto.WireBytes)
		if err := b.EncodeMessage(x.CryptoGetClaim); err != nil {
			return err
		}
	case *Query_CryptoGetProxyStakers:
		b.EncodeVarint(11<<3 | proto.WireBytes)
		if err := b.EncodeMessage(x.CryptoGetProxyStakers); err != nil {
			return err
		}
	case *Query_FileGetContents:
		b.EncodeVarint(12<<3 | proto.WireBytes)
		if err := b.EncodeMessage(x.FileGetContents); err != nil {
			return err
		}
	case *Query_FileGetInfo:
		b.EncodeVarint(13<<3 | proto.WireBytes)
		if err := b.EncodeMessage(x.FileGetInfo); err != nil {
			return err
		}
	case *Query_TransactionGetReceipt:
		b.EncodeVarint(14<<3 | proto.WireBytes)
		if err := b.EncodeMessage(x.TransactionGetReceipt); err != nil {
			return err
		}
	case *Query_TransactionGetRecord:
		b.EncodeVarint(15<<3 | proto.WireBytes)
		if err := b.EncodeMessage(x.TransactionGetRecord); err != nil {
			return err
		}
	case nil:
	default:
		return fmt.Errorf("Query.Query has unexpected type %T", x)
	}
	return nil
}

func _Query_OneofUnmarshaler(msg proto.Message, tag, wire int, b *proto.Buffer) (bool, error) {
	m := msg.(*Query)
	switch tag {
	case 1: // query.getByKey
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		msg := new(GetByKeyQuery)
		err := b.DecodeMessage(msg)
		m.Query = &Query_GetByKey{msg}
		return true, err
	case 2: // query.getBySolidityID
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		msg := new(GetBySolidityIDQuery)
		err := b.DecodeMessage(msg)
		m.Query = &Query_GetBySolidityID{msg}
		return true, err
	case 3: // query.contractCallLocal
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		msg := new(ContractCallLocalQuery)
		err := b.DecodeMessage(msg)
		m.Query = &Query_ContractCallLocal{msg}
		return true, err
	case 4: // query.contractGetInfo
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		msg := new(ContractGetInfoQuery)
		err := b.DecodeMessage(msg)
		m.Query = &Query_ContractGetInfo{msg}
		return true, err
	case 5: // query.contractGetBytecode
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		msg := new(ContractGetBytecodeQuery)
		err := b.DecodeMessage(msg)
		m.Query = &Query_ContractGetBytecode{msg}
		return true, err
	case 6: // query.ContractGetRecords
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		msg := new(ContractGetRecordsQuery)
		err := b.DecodeMessage(msg)
		m.Query = &Query_ContractGetRecords{msg}
		return true, err
	case 7: // query.cryptogetAccountBalance
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		msg := new(CryptoGetAccountBalanceQuery)
		err := b.DecodeMessage(msg)
		m.Query = &Query_CryptogetAccountBalance{msg}
		return true, err
	case 8: // query.cryptoGetAccountRecords
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		msg := new(CryptoGetAccountRecordsQuery)
		err := b.DecodeMessage(msg)
		m.Query = &Query_CryptoGetAccountRecords{msg}
		return true, err
	case 9: // query.cryptoGetInfo
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		msg := new(CryptoGetInfoQuery)
		err := b.DecodeMessage(msg)
		m.Query = &Query_CryptoGetInfo{msg}
		return true, err
	case 10: // query.cryptoGetClaim
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		msg := new(CryptoGetClaimQuery)
		err := b.DecodeMessage(msg)
		m.Query = &Query_CryptoGetClaim{msg}
		return true, err
	case 11: // query.cryptoGetProxyStakers
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		msg := new(CryptoGetStakersQuery)
		err := b.DecodeMessage(msg)
		m.Query = &Query_CryptoGetProxyStakers{msg}
		return true, err
	case 12: // query.fileGetContents
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		msg := new(FileGetContentsQuery)
		err := b.DecodeMessage(msg)
		m.Query = &Query_FileGetContents{msg}
		return true, err
	case 13: // query.fileGetInfo
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		msg := new(FileGetInfoQuery)
		err := b.DecodeMessage(msg)
		m.Query = &Query_FileGetInfo{msg}
		return true, err
	case 14: // query.transactionGetReceipt
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		msg := new(TransactionGetReceiptQuery)
		err := b.DecodeMessage(msg)
		m.Query = &Query_TransactionGetReceipt{msg}
		return true, err
	case 15: // query.transactionGetRecord
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		msg := new(TransactionGetRecordQuery)
		err := b.DecodeMessage(msg)
		m.Query = &Query_TransactionGetRecord{msg}
		return true, err
	default:
		return false, nil
	}
}

func _Query_OneofSizer(msg proto.Message) (n int) {
	m := msg.(*Query)
	// query
	switch x := m.Query.(type) {
	case *Query_GetByKey:
		s := proto.Size(x.GetByKey)
		n += 1 // tag and wire
		n += proto.SizeVarint(uint64(s))
		n += s
	case *Query_GetBySolidityID:
		s := proto.Size(x.GetBySolidityID)
		n += 1 // tag and wire
		n += proto.SizeVarint(uint64(s))
		n += s
	case *Query_ContractCallLocal:
		s := proto.Size(x.ContractCallLocal)
		n += 1 // tag and wire
		n += proto.SizeVarint(uint64(s))
		n += s
	case *Query_ContractGetInfo:
		s := proto.Size(x.ContractGetInfo)
		n += 1 // tag and wire
		n += proto.SizeVarint(uint64(s))
		n += s
	case *Query_ContractGetBytecode:
		s := proto.Size(x.ContractGetBytecode)
		n += 1 // tag and wire
		n += proto.SizeVarint(uint64(s))
		n += s
	case *Query_ContractGetRecords:
		s := proto.Size(x.ContractGetRecords)
		n += 1 // tag and wire
		n += proto.SizeVarint(uint64(s))
		n += s
	case *Query_CryptogetAccountBalance:
		s := proto.Size(x.CryptogetAccountBalance)
		n += 1 // tag and wire
		n += proto.SizeVarint(uint64(s))
		n += s
	case *Query_CryptoGetAccountRecords:
		s := proto.Size(x.CryptoGetAccountRecords)
		n += 1 // tag and wire
		n += proto.SizeVarint(uint64(s))
		n += s
	case *Query_CryptoGetInfo:
		s := proto.Size(x.CryptoGetInfo)
		n += 1 // tag and wire
		n += proto.SizeVarint(uint64(s))
		n += s
	case *Query_CryptoGetClaim:
		s := proto.Size(x.CryptoGetClaim)
		n += 1 // tag and wire
		n += proto.SizeVarint(uint64(s))
		n += s
	case *Query_CryptoGetProxyStakers:
		s := proto.Size(x.CryptoGetProxyStakers)
		n += 1 // tag and wire
		n += proto.SizeVarint(uint64(s))
		n += s
	case *Query_FileGetContents:
		s := proto.Size(x.FileGetContents)
		n += 1 // tag and wire
		n += proto.SizeVarint(uint64(s))
		n += s
	case *Query_FileGetInfo:
		s := proto.Size(x.FileGetInfo)
		n += 1 // tag and wire
		n += proto.SizeVarint(uint64(s))
		n += s
	case *Query_TransactionGetReceipt:
		s := proto.Size(x.TransactionGetReceipt)
		n += 1 // tag and wire
		n += proto.SizeVarint(uint64(s))
		n += s
	case *Query_TransactionGetRecord:
		s := proto.Size(x.TransactionGetRecord)
		n += 1 // tag and wire
		n += proto.SizeVarint(uint64(s))
		n += s
	case nil:
	default:
		panic(fmt.Sprintf("proto: unexpected type %T in oneof", x))
	}
	return n
}

func init() {
	proto.RegisterType((*Query)(nil), "proto.Query")
}

func init() { proto.RegisterFile("Query.proto", fileDescriptor_12565a3f476cd53f) }

var fileDescriptor_12565a3f476cd53f = []byte{
	// 546 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x7c, 0x94, 0x5f, 0x6f, 0xd3, 0x30,
	0x14, 0xc5, 0x29, 0xd0, 0xfd, 0x71, 0x59, 0xa7, 0x79, 0x2d, 0xf5, 0x3a, 0x06, 0x63, 0x48, 0x88,
	0xa7, 0x3e, 0x8c, 0x47, 0x9e, 0x96, 0x4e, 0x94, 0x09, 0x90, 0xca, 0x3a, 0x21, 0xf1, 0x84, 0x8c,
	0xe3, 0xb6, 0x81, 0x2c, 0x0e, 0xee, 0x1d, 0x22, 0x5f, 0x88, 0xcf, 0x89, 0x7a, 0x6b, 0xa7, 0xb1,
	0xe3, 0xee, 0xa9, 0xea, 0x3d, 0xf7, 0xfc, 0xe2, 0xe4, 0x9e, 0x6b, 0xd2, 0xfa, 0x72, 0x27, 0x75,
	0x31, 0xc8, 0xb5, 0x02, 0x45, 0x9b, 0xf8, 0xd3, 0x6f, 0x8f, 0x24, 0x44, 0xc5, 0x47, 0x69, 0xca,
	0xfd, 0x2e, 0xfe, 0x9f, 0xa8, 0x34, 0x89, 0x13, 0x28, 0xae, 0x2e, 0x4d, 0xb9, 0x37, 0x54, 0x19,
	0x68, 0x2e, 0x60, 0xc8, 0xd3, 0xf4, 0x93, 0x12, 0x3c, 0xb5, 0xfd, 0x56, 0x18, 0x49, 0xb8, 0xca,
	0xa6, 0xca, 0x94, 0x8f, 0x2a, 0xe5, 0xa8, 0x00, 0x29, 0x54, 0x2c, 0x8d, 0xc4, 0x2a, 0xd2, 0xb5,
	0x14, 0x4a, 0xc7, 0x0b, 0xa3, 0x9c, 0x0c, 0x75, 0x91, 0x83, 0x1a, 0x49, 0xb8, 0x10, 0x42, 0xdd,
	0x65, 0x10, 0xf1, 0x94, 0x67, 0x42, 0x6e, 0x92, 0x5d, 0xf7, 0x61, 0x29, 0x57, 0xce, 0xd1, 0x29,
	0x8b, 0xc3, 0x94, 0x27, 0xb7, 0xa6, 0xfa, 0xb4, 0xac, 0x4e, 0x80, 0xff, 0x92, 0xda, 0x22, 0xba,
	0xef, 0x93, 0x54, 0x2e, 0x7b, 0x55, 0x06, 0x32, 0x03, 0x5b, 0x3e, 0x30, 0xe5, 0x0a, 0xf7, 0xf8,
	0x46, 0xf3, 0x6c, 0xc1, 0x05, 0x24, 0x2a, 0x5b, 0xbd, 0x87, 0x4c, 0x72, 0x30, 0x62, 0xbf, 0x26,
	0x2a, 0x1d, 0xaf, 0xb4, 0xb3, 0x7f, 0xbb, 0xa4, 0x89, 0x63, 0xa0, 0xe7, 0x64, 0x67, 0x66, 0xbe,
	0x3d, 0x6b, 0x9c, 0x36, 0xde, 0xb4, 0xce, 0x3b, 0xab, 0x9e, 0x81, 0x1d, 0x09, 0xf6, 0x7d, 0x78,
	0x70, 0x5d, 0xf6, 0xd1, 0x11, 0xd9, 0x9f, 0xb9, 0xf3, 0x61, 0x0f, 0xd1, 0x7a, 0x5c, 0xb5, 0xae,
	0x55, 0x4b, 0xf0, 0x5d, 0xf4, 0x33, 0x39, 0x10, 0xfe, 0x44, 0xd9, 0x23, 0x44, 0x9d, 0x18, 0x54,
	0x6d, 0xe2, 0x16, 0x56, 0x77, 0x2e, 0xcf, 0x25, 0xdc, 0x1c, 0xb0, 0xc7, 0xce, 0xb9, 0xbc, 0x94,
	0x94, 0xe7, 0xf2, 0x5c, 0x74, 0x42, 0x0e, 0x45, 0x3d, 0x39, 0xac, 0x89, 0xb0, 0x17, 0x75, 0x98,
	0xed, 0xb0, 0xc0, 0x90, 0x9b, 0x8e, 0x09, 0xad, 0x67, 0x8e, 0x6d, 0x21, 0xf3, 0x79, 0x9d, 0x69,
	0x1a, 0x2c, 0x32, 0xe0, 0xa5, 0xdf, 0x49, 0x4f, 0x60, 0x84, 0x66, 0x7e, 0x56, 0xd9, 0x36, 0x62,
	0x5f, 0x59, 0x6c, 0x38, 0xd1, 0x96, 0xbd, 0x89, 0xb2, 0x7e, 0x40, 0x2d, 0xed, 0x6c, 0xe7, 0xde,
	0x07, 0x78, 0x87, 0xdf, 0x44, 0xa1, 0x17, 0x64, 0x4f, 0x54, 0xf7, 0x85, 0xed, 0x22, 0xf6, 0xc8,
	0xc7, 0x56, 0xa7, 0xe5, 0x3a, 0xe8, 0x25, 0x69, 0x0b, 0x67, 0xbb, 0x18, 0x41, 0x46, 0xdf, 0x67,
	0xa0, 0x68, 0x21, 0x9e, 0x87, 0xde, 0x90, 0x6e, 0x59, 0x19, 0x6b, 0xf5, 0xb7, 0x30, 0x2b, 0xc9,
	0x5a, 0x08, 0x7b, 0xe6, 0xc3, 0x8c, 0x6c, 0x71, 0x61, 0xf3, 0x32, 0x90, 0x53, 0x77, 0x97, 0xd9,
	0x13, 0x27, 0x90, 0xde, 0xa6, 0x97, 0x81, 0xf4, 0x5c, 0xf4, 0x1d, 0x69, 0x4d, 0xd7, 0xdb, 0xcf,
	0xf6, 0x10, 0xd2, 0x73, 0x21, 0xd5, 0x6f, 0x54, 0xed, 0xa6, 0xdf, 0x48, 0x17, 0x42, 0xf7, 0x04,
	0x6b, 0x23, 0xe6, 0xa5, 0xc1, 0x04, 0xef, 0x92, 0xf2, 0x05, 0x83, 0x04, 0xfa, 0x95, 0x74, 0x20,
	0x70, 0xcb, 0xb0, 0x7d, 0x24, 0x9f, 0x6e, 0x22, 0x2b, 0x1d, 0x5b, 0x70, 0xd0, 0x1f, 0x6d, 0x93,
	0xe6, 0xef, 0x65, 0x43, 0xf4, 0x9a, 0x9c, 0x09, 0x75, 0x3b, 0x98, 0xcb, 0x58, 0x6a, 0x3e, 0xe7,
	0x8b, 0xf9, 0x4c, 0xf3, 0x7c, 0x3e, 0xe0, 0x79, 0x62, 0xd8, 0x3f, 0xf9, 0x1f, 0x3e, 0x6e, 0xfc,
	0xd8, 0xc2, 0x7f, 0x6f, 0xff, 0x07, 0x00, 0x00, 0xff, 0xff, 0xd8, 0xef, 0x64, 0xed, 0x5d, 0x06,
	0x00, 0x00,
}
